version: '3'

services:
  backend:
    build: backend/
    restart: on-failure
    depends_on:
      - 'database'

    ports: 
      - '8081:8081'

    volumes:
      - ./backend:/var/lib/postgresql/back    
    command: npm run db

  frontend:
    build: frontend/
    depends_on:
      - 'backend'
    ports:
      - '3000:3000'

    volumes:
      - ./frontend:/var/lib/postgresql/front      

  database:
    image: postgres:latest
    container_name: pg-docker
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: inventory
      DATABASE_URL: postgres://postgres:docker@backend:5432/inventory

    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    restart: always